In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('call.xlsx', encoding='utf-8')

In [3]:
# df=df.sort_values(['date'])
# df=df.reset_index(drop=True)

In [4]:
df=df.set_index(['date'])

In [5]:
new_df=df.loc[:'2005-01-01']

In [6]:
from datetime import timedelta
updown=[]
for idx in df.index:
        time = idx - pd.DateOffset(months=1)
        
        while True:
            if idx.year <= 2004 : break
            
            try:
                if df.loc[idx][0]>df.loc[time][0] : updown.append('상승')
                elif df.loc[idx][0]<df.loc[time][0]: updown.append('하락')
                else : updown.append('0')
                break
            except:
                time-=timedelta(1)
                continue

In [7]:
new_df['UpDown']=updown

C:\Users\tjlee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [8]:
new_df

            price UpDown
date
2019-07-15   1.73     하락
2019-07-12   1.74     하락
2019-07-11   1.75      0
2019-07-10   1.74     하락
2019-07-09   1.69     하락
2019-07-08   1.73     하락
2019-07-05   1.73      0
2019-07-04   1.73     하락
2019-07-03   1.73     하락
2019-07-02   1.73     하락
2019-07-01   1.75     하락
2019-06-28   1.83     상승
2019-06-27   1.77     상승
2019-06-26   1.76     상승
2019-06-25   1.75     상승
2019-06-24   1.75     상승
2019-06-21   1.74     상승
2019-06-20   1.75     하락
2019-06-19   1.76     상승
2019-06-18   1.75     상승
2019-06-17   1.76     상승
2019-06-14   1.74     상승
2019-06-13   1.75      0
2019-06-12   1.75     상승
2019-06-11   1.75     상승
2019-06-10   1.75     상승
2019-06-07   1.77     상승
2019-06-05   1.73     하락
2019-06-04   1.75     상승
2019-06-03   1.77     상승
...           ...    ...
2005-02-16   3.26      0
2005-02-15   3.26      0
2005-02-14   3.26      0
2005-02-11   3.27     하락
2005-02-07   3.18     하락
2005-02-04   3.22     하락
2005-02-03   3.26     하락
2005-02-02   3.25     하락
2005-02-01   3.26     하락
2005-01-31   3.26     하락
2005-01-28   3.25     하락
2005-01-27   3.24     하락
2005-01-26   3.26     하락
2005-01-25   3.25     하락
2005-01-24   3.25     하락
2005-01-21   3.19     하락
2005-01-20   3.23     하락
2005-01-19   3.25     하락
2005-01-18   3.25     하락
2005-01-17   3.25     하락
2005-01-14   3.26     하락
2005-01-13   3.28      0
2005-01-12   3.27     하락
2005-01-11   3.28      0
2005-01-10   3.27     하락
2005-01-07   3.22     상승
2005-01-06   3.21     하락
2005-01-05   3.28     상승
2005-01-04   3.27     상승
2005-01-03   3.27     상승

[3606 rows x 2 columns]

In [9]:
new_df.to_excel('콜금리_updown.xlsx', sheet_name='Sheet1',encoding='utf-8')